# Generated by Django 4.2.8 on 2023-12-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='telegram id для уведомлений'),
        ),
    ]
